version: "3"
services:
  tree-app-backend:
    image: michaelunknown/mkpoker-webapp-backend-arm:latest
    environment:
      PORT: 3080
    ports:
      - 3080:3080
  tree-app-frontend:
    image: michaelunknown/mkpoker-webapp-frontend-arm:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
